- name: PLAY1
  hosts: local
  connection: local
  tasks:
  - name: hello from play 1 ans task1
    ansible.builtin.debug:
      msg: "Hello from PLAY-1 ans TASK-1"

  - name: hello from play 1 ans task2
    ansible.builtin.debug:
      msg: "Hello from PLAY-1 ans TASK-2"

- name: PLAY2
  hosts: local
  connection: local
  tasks:
  - name: hello from play 2 ans task1
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 ans TASK-1"

  - name: hello from play 2 ans task2
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 ans TASK-2"      