- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible # equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
    DURATION: 10hr
    TRAINER: Sridhar
  tasks:
  - name: print course information
    ansible.builtin.debug:
    # vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course {{ DURATION }}: 10hr, Trainer is {{ TRAINER }}"