- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS # equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
    DURATION: 10hr
    TRAINER: Sridhar
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
    # vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"
  tasks:
  - name: print course information again
    ansible.builtin.debug:
    # vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"      