- name: install packages
  hosts: frontend
  become: yes
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - zip