- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, Srikanth, John, Jane"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"    
  
  - name: convert map into list
    vars: 
      course:
        name: ansible
        duration: 10hr
        trainer: Sridhar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list into map
    vars: 
      course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10hr'}
        - {'key': 'trainer', 'value': 'Sridhar'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"      

  - name: convert to uppercase
    vars: 
      name: "Sridhar Kothapalli"  
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"  

  - name: convert to lowercase
    vars: 
      name: "Sridhar Kothapalli"  
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"  

  - name: check IP address is valid or not
    vars:
      ip: "300.567.988.789"
    ansible.builtin.debug:
      msg: "is {{ ip | ansible.utils.ipaddr }}"             