- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, Srikanth, John, Jane"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"    
  
  - name: convert map into list
    vars: 
      course:
        name: ansible
        duration: 10hr
        trainer: Sridhar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"